import time

print("----------Welcome to my refactored Reddit web scraper!----------")
time.sleep(2)
print("")
print("This project makes use of three source files in three directories.")
time.sleep(2)
print("")
print("Each source file is logically unique and completes a separate task (this is one of those source files!)")
time.sleep(2)
print("")
print("If you need more details on functionality, check out the README in GitHub and also consult the comments atop each source file.")
time.sleep(2)
print("")
print("That's all for now- enjoy the tool!")